#!/bin/bash
set -x

cat > /usr/share/nginx/html/index.html <<EOF
<html>
<body style="background-color: $COLOR">
<h1>TUDTA?</h1>
<p>$BODY</p>
<hr/>
<p>host: $HOSTNAME</p>
</body>
</html>
EOF

nginx -g "daemon off;"
